spring:
  application:
    name: ServiceCenter

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

security:
  user:
    name: root
    password: root

server:
  port: 8073

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8079/eureka/


  mail:
    host: smtp.gmail.com
    port: 587
    username: nousemail77@gmail.com  # Replace with your actual Gmail address
    password: xidvfirbixsmwfja          # Replace with your actual Gmail password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

